########################################################################################################################
FROM ghcr.io/mainsail-crew/virtual-klipper-printer:v0.13.0-573 AS base
COPY --chmod=0755 --chown=root:root avrsim_dual.py /opt/klipper/avrsim_dual.py
